---
name: docker-CI
on:
  push:
    branches: [ main ]

env:
  AZURE_REGISTRY: flashyacr.azurecr.io
  AZURE_REPOSITORY: ${{ github.repository }}
  AZURE_TOKEN_NAME: ${{ github.event.repository.name }}

jobs:
  get-token-access:
    runs-on: ubuntu-latest
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: Flash1212
          repo: actions-create-acr-scoped-token
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          workflow_file_name: acr-scoped-credentials.yaml
          ref: main
          wait_interval: 10
          inputs: '{"AZURE_REPOSITORY": "${{ env.AZURE_REPOSITORY }}", "AZURE_REGISTRY": "${{ env.AZURE_REGISTRY }}", "AZURE_TOKEN_NAME": "${{ env.AZURE_TOKEN_NAME }}"}'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
  docker-work:
    runs-on: ubuntu-latest
    needs: get-token-access
    steps:
      - name: Docker build
        run: |
          printf "FROM alpine\nENTRYPOINT [ "bin/sh" ]" >> Dockerfile
          docker build . -t ${AZURE_REGISTRY,,}/${AZURE_REPOSITORY,,}
          docker login ${AZURE_REGISTRY,,} \
          --username ${{ secrets.AZURE_TOKEN_USERNAME }} \
          --password ${{ secrets.AZURE_TOKEN }}
          docker push ${AZURE_REGISTRY,,}/${AZURE_REPOSITORY,,}
